# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jason
email: ksjifjui@sina.com
description: >- # this means to ignore newlines until "baseurl:"
  C#、Javascript developer comes from China.
github_username:  jasonLiu001

# 保存所有评论的github库
github_comments_repository:  jasonLiu001/github-pages-comments

# 文章分页设置
paginate: 10
paginate_path: "/page:num/"

#theme: jekyll-theme-midnight
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# 设置sass样式目录
sass:
  sass_dir: _sass

# 设置所有文章的默认布局等信息
defaults:
  -
     scope:
      path: ""
      type: "posts"
     values:
      layout: "post"
      author: "Jason Liu"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "readme.md", "package.json"]
